name: ai_sulama
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.11
  tflite_flutter: ^0.11.0
  flutter_local_notifications: ^19.3.1
  device_info_plus: ^11.5.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/model/irrigation_model.tflite
  uses-material-design: true

